#!/bin/bash

#### Start with: /Result/Orthogroup_Sequences

#### Step 1: Filtered Orthogroups to contain at least one transcript for each species 
## 1.1 Filtered Ortho IDs - Idea: filter it here: /ResultOrthogroups/Orthogroups.GeneCount.tsv
## Source: https://github.com/davidemms/OrthoFinder/issues/154
## E.g. for the example dataset I used the excel commands =COUNTIF(B3,">0"), =SUM(G2:J2) and =K2=4 as shown here: Orthogroups.GeneCount.xlsx

## 1.2 Filtered Ortho files - Idea: asking...

#### Step 2: 



### Assessment
# Mado de novo path: /home/justinma/CS_RNAseq/kraken/M_runDrap/e-rmbt_editing/all_contigs.second_pass.fa
# Abu de novo path: /home/justinma/CS_RNAseq/kraken/Abu_runDrap/e-rmbt_editing/all_contigs.second_pass.fa

## Assess de novo assembly
busco \
    -f \
    -i /home/justinma/CS_RNAseq/kraken/M_runDrap/e-rmbt_editing/all_contigs.second_pass.fa \
    -o busco_M \
    -m tran \
    --out_path /home/justinma/shoaling_analysis/busco \
    -l actinopterygii_odb12 \
    -c 13

busco \
    -f \
    -i /home/justinma/CS_RNAseq/kraken/Abu_runDrap/e-rmbt_editing/all_contigs.second_pass.fa \
    -o busco_Abu \
    -m tran \
    --out_path /home/justinma/shoaling_analysis/busco \
    -l actinopterygii_odb12 \
    -c 13

## Build DIAMOND database
diamond makedb --in uniprot_sprot.fasta --db swissprot.dmnd --threads 14

## Blastp - Abu (Diamond)
diamond blastp \
    -d swissprot.dmnd \
    -q Abu_pep.fasta \
    -o Abu_vs_swissprot.tsv \
    --threads 14 \
    --max-target-seqs 15 \
    --ultra-sensitive \
    --evalue 1e-5 \
    --outfmt 6

## Blastp - M (Diamond)
diamond blastp \
    -d swissprot.dmnd \
    -q M_pep.fasta \
    -o M_vs_swissprot.tsv \
    --threads 14 \
    --max-target-seqs 15 \
    --ultra-sensitive \
    --evalue 1e-5 \
    --outfmt 6

#### Quant

# Salmon - Index
cat M_pep.fasta Abu_pep.fasta > all_pep.fasta
salmon index --threads 14 --index cluster_index --transcripts all_pep.fasta

# Salmon - Quantification
mkdir -p quant_result

# 遍历所有 *_1.fq.gz 文件
for R1 in /home/justinma/CS_RNAseq/kraken/*_1.fq.gz
do
    # 找到对应的 R2 文件
    R2=${R1/_1.fq.gz/_2.fq.gz}

    # 样本名：去掉路径和后缀
    samp=$(basename "$R1" _1.fq.gz)

    echo "Processing sample ${samp}"

    salmon quant -i cluster_index -l A \
        --gcBias \
        -1 "$R1" \
        -2 "$R2" \
        -p 14 --validateMappings \
        -o quant_result/${samp}_quant
done







